version: '3.8'

services:
  database:
    container_name: db_chess
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 4ahitn
      MYSQL_DATABASE: 4ahitn
      MYSQL_USER: 4ahitn
      MYSQL_PASSWORD: 4ahitn
    ports:
      - '4306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
